name: msu-synovitis-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - xgboost=3.0.0
  - lightgbm=4.6.0
  - catboost=1.2.8
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - numpy=2.0.1
